// <auto-generated />
using System;
using CapaData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapaData.Migrations.Data
{
    [DbContext(typeof(DB_Context))]
    [Migration("20251118220259_AddMenuTable")]
    partial class AddMenuTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapaData.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attach")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescripcionMenu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdPadre")
                        .HasColumnType("int");

                    b.Property<string>("RolesUsers")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdPadre");

                    b.ToTable("Menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attach = "",
                            DescripcionMenu = "Administracion"
                        },
                        new
                        {
                            Id = 2,
                            Attach = "Roles/Index",
                            DescripcionMenu = "Roles",
                            IdPadre = 1
                        },
                        new
                        {
                            Id = 3,
                            Attach = "UserRoles/Index",
                            DescripcionMenu = "Usuarios",
                            IdPadre = 1
                        },
                        new
                        {
                            Id = 4,
                            Attach = "Menus/Index",
                            DescripcionMenu = "Menus",
                            IdPadre = 1
                        });
                });

            modelBuilder.Entity("CapaData.Entities.Menu", b =>
                {
                    b.HasOne("CapaData.Entities.Menu", null)
                        .WithMany()
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
